### ISSUE TITLE
Actors that are parents to other actors won't run scripts

### ISSUE THREAD

**Issue by Lizband** [deadcast2/UltraEd#106]
If an actor is the parent of an object then it won't allow a script to run on it.

**Comment by deadcast2** [comment]
I'll try this out and see what results I get.

**Comment by deadcast2** [comment]
Ok this should be fixed now. Great job finding this issue! Totally missed testing this out once I got the parent/child actor system implemented. Still some things wonky but it seems the bug list is getting smaller.
