### ISSUE TITLE
Debug Error!    abort() has been called

### ISSUE THREAD

**Issue by Sammyueru** [deadcast2/UltraEd#130]
So I built ultraEd in visual studio and got this error:
![image](https://user-images.githubusercontent.com/60794497/148464744-12f849b9-41a1-48c0-9a2a-5bdf290762ce.png)
I got some warnings in visual studio though:
![image](https://user-images.githubusercontent.com/60794497/148464943-a1b99ad9-fb60-42ee-87fe-ad159133a6e8.png)
P.S. I can run it with the local windows debugger for some odd reason./
But I do want to be able to have the .exe to work because I also can't build rom's for some reason in there

**Comment by deadcast2** [comment]
Hi Sammyueru! Do you have the DirectX sdk installed? If not you can obtain from here https://www.microsoft.com/en-us/download/details.aspx?id=6812

I think I had that same problem a few days back when I refreshed my machine.
