### ISSUE TITLE
Swapping Meshes Through Code

### ISSUE THREAD

**Issue by EGAMatsu** [deadcast2/UltraEd#136]
Define Mesh A's name and Mesh B's name, then set self->mesh to the mesh name if need be
Maybe interpolate them if possible for smooth animations.

**Comment by deadcast2** [comment]
What types of scenarios are you thinking about where that would be useful? Trying to imagine currently were I would, for instance, use that.

**Comment by EGAMatsu** [comment]
Vertex animation
