### ISSUE TITLE
Question: How to use custom functions

### ISSUE THREAD

**Issue by Lizband** [deadcast2/UltraEd#142]
In the description you mention `Actor *FindActorByName(const char *name)` & `void SetActiveCamera(Actor *camera)`. Can you give examples on how to use the functions? I tried a few different ways of trying to execute them, but that either results in an error (most likely due to incorrect usage of the function) or no observable change.

**Comment by deadcast2** [comment]
Yeah sure, its use is pretty simple. First locate the camera actor you want by name and then set it to active like this:

```
Actor *altCamera = FindActorByName("Alt Camera");
if (altCamera != NULL)
{
    SetActiveCamera(altCamera);
}
```

I just pushed a small change that makes sure the default camera selector runs before executing the script Start routines so you can manually set a default. For example in a Start:

```
void $Start(Actor *self)
{
    SetActiveCamera(self);
}
```

**Comment by Lizband** [comment]
Thank you so much!
