### ISSUE TITLE
Shift keys keep user from using backspace in script editor

### ISSUE THREAD

**Issue by Lizband** [deadcast2/UltraEd#143]
Issue:
If the user holds [Shift] and tries to backspace a character, the script editor will not register the input as a backspace.

Expected result:
If the [Shift] key is held and backspace is pressed, the character should still be backspaced.

**Comment by deadcast2** [comment]
Ok fixed! Pretty easy little change to the text editor plugin being used. Not sure why that action wasn't allowed? Also sorry if you experience any ROM building errors when pulling down the latest UltraEd. I did a lot of class and variable renaming today to improve clarity. Getting really old todo list items finally done.

**Comment by Lizband** [comment]
Thanks again!
