### ISSUE TITLE
what language is this?

### ISSUE THREAD

**Issue by DriftWare07** [deadcast2/UltraEd#152]

**Comment by Byterset** [comment]
You mean the programming language used? Mostly c and c++ but github also provides an overwiew of the languages used on the repo overview.

**Comment by deadcast2** [comment]
Yeah @Byterset is correct. The editor is written in C++, the N64 engine components in C and the scripting language used inside the editor to program actors is C.

**Comment by DriftWare07** [comment]
aw cool. Now i wish i knew c. Does it exports roms yet?

**Comment by deadcast2** [comment]
Yeah UltraEd does export working ROMs that are runnable on the cen64 emulator, project 64 emulator, 64Drive cart and the EverDrive cart.
