### ISSUE TITLE
Rotation in script does not work

### ISSUE THREAD

**Issue by guighub** [deadcast2/UltraEd#164]
Here's my code example: 

```
void $Update(Actor *self)
{
    // Called every frame.
    self->rotationAxis.y += 0.2f;
}
```
I put the code on an actor and saved it, did everything to build and it will not rotate. Translating an object does work though.

**Comment by deadcast2** [comment]
Hey! You actually need to increment the rotationAngle to get the actor to rotate. The rotationAxis is for setting which axis the rotation will occur on. The rotation needs some improvement like allowing to rotate in either local or world space but it's pretty functional for now.
