### ISSUE TITLE
Whenever I set a texture to an actor I get Invalid dimensions 

### ISSUE THREAD

**Issue by Hunterrules0-0** [deadcast2/UltraEd#171]
Why does this happen and what do you have to do to prevent this

**Comment by Hunterrules0-0** [comment]
nevermind I just realized that it has to be a size of 16, 32, 64

**Comment by deadcast2** [comment]
Yeah you got it. The 64x64 isn't working though and I haven't yet figured it out. 16x16 and 32x32 are fine though.
