### ISSUE TITLE
Binary downloads?

### ISSUE THREAD

**Issue by Cobradabest** [deadcast2/UltraEd#4]
Is it possible that you'll provide pre-built binaries sometime in the future? I would love to try this, but I'm not comfortable installing Visual Studio (Something I can't uninstall afterwards) just to build this.

**Comment by deadcast2** [comment]
Hello! Sorry I missed this!

Yeah I definitely will provide an installer/pre-built binary eventually. I think I'd like to get sphere based collision detection finished, smash a few more UI bugs and then have an official release. Getting some basic collision detection will really allow more fun things to be made. Now collision response is something I haven't started yet on though.... lol.
