### ISSUE TITLE
when building rom it said  libiconv-2.dll and libwinpthread-1.dll are not found

### ISSUE THREAD

**Issue by dmoreland117** [deadcast2/UltraEd#46]
when building rom it said  libiconv-2.dll and libwinpthread-1.dll are not found. then it said build failed make sure build tools are installed(i did install them). but other than that i love it

**Comment by deadcast2** [comment]
Oh no! Sorry to hear you ran into build problems. To help me debug what OS are you using and what compiler did you use?

**Comment by dmoreland117** [comment]
i am on windows 10 and i used visual studio 2019

**Comment by dmoreland117** [comment]
i can use the editor the only problem is when i click build rom

**Comment by deadcast2** [comment]
Cool thanks. Let me get a clean Win 10 machine put together so I can try and see if I need to rebuild the custom GNU compiler. Might have to static link some additional libraries. I'll let you know what I find once I trouble shoot some more. Glad though you're liking the editor so far! Long way to go still lol. :)

**Comment by dmoreland117** [comment]
yah i love the idea of this... i dont know a lot of c or c++ but im getting there :) the error is with a file called mips64-elf-gcc.exe

**Comment by dmoreland117** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/61122492/74880367-ae897100-5330-11ea-9427-91deac520781.png)
![Screenshot (4)](https://user-images.githubusercontent.com/61122492/74880378-b2b58e80-5330-11ea-9fd3-3f536a4c5dbf.png)

here are some screenshots if that helps any

**Comment by deadcast2** [comment]
Thanks for the screen shots! I was able to reproduce your errors about the missing libraries. I'll have to see about building a new compiler that includes those libs statically or just bundle the DLLs with the compiler. I believe those libraries are from the MinGW environment. I'll investigate how I originally built the custom compiler and then apply a fix. 

I'll keep this ticket posted with my progress. Sorry for the delay while I sort this out. In the meantime you could install MinGW and see if those DLLs are included. If so you could then add them into the Editor folder for UltraEd. Hacky but could work for now. :)

**Comment by dmoreland117** [comment]
i found the dll files in another program i have called retro arch and putt them in the same folder as mips64-elf-gcc and it build fine now

**Comment by deadcast2** [comment]
Great, glad you got things working. I just pushed a commit that now fixes the problem so anyone in the future should be fine now. Thanks for reporting the issue to me and UltraEd is now better for it! :)
