### ISSUE TITLE
No arrows are appearing to move or rotate models.

### ISSUE THREAD

**Issue by Cobradabest** [deadcast2/UltraEd#6]
When I import a model into the game, it doesn't let me move or rotate it, even when the model is selected.

What do I do?

**Comment by deadcast2** [comment]
Hmm interesting. Could you by chance provide me the model so I could further investigate what may be causing the mouse picking issue? Thanks!

**Comment by Cobradabest** [comment]
Oh, sure, here you go: https://www.mediafire.com/file/2es5kwrdigefu94/forklift.obj/file

**Comment by deadcast2** [comment]
Great thanks!

Strange but for me I'm able to easily manipulate the model. Does it behave at all like this:
![suhgj](https://user-images.githubusercontent.com/45521946/61583260-5d8b7300-aaea-11e9-857f-8fb4273cc889.gif)

I know there are some control focusing problems after I introduced the treeview control on the left. I probably have some code mishandling the win32 input messages somewhere. Pull down the latest code and see if that makes any difference. I have made some small, various changes. : )

**Comment by Cobradabest** [comment]
Nope, the arrows you click on to move and rotate the model don't show.
![image](https://user-images.githubusercontent.com/8548727/61583793-ef1fd280-ab34-11e9-869b-33ecc15e5e69.png)
Also, I accidentally sent you the wrong file. My version of the editor can't load obj files, only 3ds ones, the above is the 3ds file. Here's the 3ds version of the file: https://www.mediafire.com/file/fmsv89bawhcoimk/forklift.3ds/file

**Comment by deadcast2** [comment]
I can't seem to download the 3ds file. The link just takes me to a page saying "Download not available". Maybe it needs to be re-uploaded?

**Comment by Cobradabest** [comment]
Sorry, try this: https://www.mediafire.com/file/pvbp59lsy9bjm8q/forklift.3ds/file

**Comment by deadcast2** [comment]
Cool got it! I just pushed a change that fixes a picking bug in the editor that I think was causing the issue. Pull down the latest code and see now if you're able to select the model.
