### ISSUE TITLE
"Deps\DXSDK\Lib\x64\d3d9.lob : fatal error LNK1107: invalid or corrupt file: cannot read at 0x81"

### ISSUE THREAD

**Issue by Cobradabest** [deadcast2/UltraEd#65]
I get the following error when I try to build UltraEd on VisualStudio 2019 Community on Windows 10 64-bit:
![devenv_MjRqxYaeT8](https://user-images.githubusercontent.com/8548727/93724999-979b4d80-fba3-11ea-9a92-a15c4f3078e6.png)

**Comment by deadcast2** [comment]
Hello!

Are you making sure to compile the project as a 64 bit application?

![Capture](https://user-images.githubusercontent.com/45521946/93788811-f386c600-fbe5-11ea-9354-c7db45b2465c.PNG)

**Comment by Cobradabest** [comment]
Yeah, it was set to x64 by default.

**Comment by deadcast2** [comment]
Ok cool.

I think I know what the problem is now. I recently switched the repository to use LFS for all binary files and I bet the lib files haven't been fully downloaded yet in your project and are still pointer files. Unfortunately github doesn't include those files when you download the zipped project. I'll have to update the readme today to make this known.

So to get the files checkout the project via `git clone https://github.com/deadcast2/UltraEd.git` instead and then once inside the root of the project run `git lfs pull`. That command should then fully download the pointer files and you then should be able to compile.

**Comment by Cobradabest** [comment]
I get this error when I try to run `git lfs pull`: `bash: $'\302\226git': command not found`

**Comment by deadcast2** [comment]
Hmm did you maybe copy and paste that command? Looks like some junk characters got copied. Also did the clone work okay?

**Comment by Cobradabest** [comment]
The clone worked just fine, I'll try and type the second command in a bit.

**Comment by Cobradabest** [comment]
Okay, typing in the command manually worked. However, building the project still gave me the same errors.

**Comment by deadcast2** [comment]
Cool glad the command worked but that's strange that you're still getting that error. In the folder Deps\DXSDK\Lib\x64\ do the files there have a size of 1KB? They should all be greater than that.

![Capture](https://user-images.githubusercontent.com/45521946/94604260-44349980-024c-11eb-9eb8-707467a86389.PNG)

I'm wondering if the files still haven't really downloaded yet from GitHub.

**Comment by Cobradabest** [comment]
They are not, they're all just a several hundred bytes each.

**Comment by deadcast2** [comment]
Ok, I would then start all of the way over. Make sure to have the latest version of Git and then re-clone a fresh copy of the project. I would just run these commands:

1. `git clone https://github.com/deadcast2/UltraEd.git`
2. `cd UltraEd && git lfs pull`

That should work but if not let me know. Wish I didn't have to use Git LFS for binary storage but their repo limits are quite small.

**Comment by Cobradabest** [comment]
I did that, I'm getting the exact same problem.

**Comment by deadcast2** [comment]
That's strange it's still not fully downloading the files. I went ahead and put together a zip file of the whole project from the master branch containing all files. https://ln2.sync.com/dl/9e2f50f40/jdcv2kea-rk7ngkdz-dye6prnw-8qpj3dmm

Sorry it's been such a pain and hopefully the download link will let you get started quickly. Still have to compile but all files are present now.

**Comment by Cobradabest** [comment]
That worked, thanks a lot! 😸 

I have another issue, but I should probably open a new issue for that!
