### ISSUE TITLE
Actors not appearing in editor

### ISSUE THREAD

**Issue by Cobradabest** [deadcast2/UltraEd#70]
So I finally got the editor building, and I tried to import some models I made and a camera, but neither seem to appear in the editor at all.

How to recreate:

1. Get files from [Here](https://github.com/deadcast2/UltraEd/issues/65#issuecomment-707215912)
2. Build it using VS2019 Community on Windows 10 (x64 Debug)
3. Add a camera of model by clicking (Actor > Camera/Model)

![image](https://user-images.githubusercontent.com/8548727/95779201-8a184580-0cc1-11eb-828b-822fc010602f.png)

**Comment by deadcast2** [comment]
Hello!

There's been a lot of changes in the current active branch **asset-tracking** that may fix this issue. It's getting closer to being done so I can then merge that into the master branch to be ready for use. In the meantime you could check out the asset-tracking branch. I need to write some documentation on how to use the new project feature in UltraEd.
