### ISSUE TITLE
Not able to run .sln due to following error: Vendor\DXSDK\Lib\x64\d3d9.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x81

### ISSUE THREAD

**Issue by Lizband** [deadcast2/UltraEd#73]
Upon trying to build any recent versions of UltraED Visual Studio throws up this error `Vendor\DXSDK\Lib\x64\d3d9.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x81`

**Comment by deadcast2** [comment]
Hello!

It's probably due to not fully downloading all of the files for the project. This repo uses Git LFS for large file blobs so in your ultraed root folder, where you git cloned to, make sure to run `git lfs pull`. That should then grab all files needed to build.
