### ISSUE TITLE
Models disappear when reloading a project

### ISSUE THREAD

**Issue by Lizband** [deadcast2/UltraEd#80]
When adding custom models or textures to a project and saving a scene then upon the next time a user loads the scene the models are gone. They still appear in the Scene Graph, but do not in the Scene View or upon building the project.

**Comment by deadcast2** [comment]
Hello, could you send me your example project? I'm not able to reproduce the issue. Models and textures are loading fine when I re-open a scene in a new project.

**Comment by Lizband** [comment]
The repo or the project files?

**Comment by deadcast2** [comment]
Just the project files.

**Comment by Lizband** [comment]
Will do.

**Comment by Lizband** [comment]
[https://drive.google.com/file/d/1tQSFploIYHtnb2h_6r19s4gD9o4tLhtz/view?usp=sharing](url)

**Comment by Lizband** [comment]
Title.scene is the one I'm having the issues with.

**Comment by Lizband** [comment]
It seems that the issue has stopped occurring now. I'm not sure what was causing it.
