### ISSUE TITLE
Swap out legacy makemask for new replacement makemask

### ISSUE THREAD

**Issue by nterry** [deadcast2/UltraEd#83]
The makemask provided by the n64 sdk is really old and is only 32 bit.

The guy who wrote spicy, also wrote a replacement. See https://github.com/trhodeos/makemask

Maybe it should be replaced? I tested it out with a sample scene and it compiled and ran on the bundled cen64.

Im not an expert on n64 toolchains, but I think it is worth investigating.

**Comment by deadcast2** [comment]
The makemask included in UltraEd is actually the one from the repository you mention. I'm very thankful for that guy's work! Also spicy is amazing as well. :)
